name: Test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: denolib/setup-deno@master
      with:
        deno-version: 0.27.0
    - run: deno test --allow-net --allow-run --allow-env --allow-write
